spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: leo
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
  h2:
      console:
        enabled: true
        path: /h2-console
        settings:
          trace: false
          web-allow-others: false
